name: random_person_data
description: A Dart package for fetching random user data from the Random User Generator API.
version: 1.0.0
homepage: https://github.com/jony1346/random_person_data

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android: null
      ios: null
      web: null
      windows: null
      linux: null
      macos: null